ifdef ACTIVE_GPU
	CC := nvcc
	INC_DIRS := 
	FLAGS := --compiler-bindir `which mpic++` -arch=sm_70 -x cu
	LIBRARIES := -I/usr/include/gdal -lgdal
	DFLAGS := -DACTIVE_GPU=1
else
	CC := mpic++
	INC_DIRS := 
	FLAGS := -Wall -fopenmp
	LIBRARIES := -I/usr/include/gdal -lgdal
	DFLAGS := -DACTIVE_OMP=1
endif

triton: $(SRCDIR)/main.cpp
	if [ ! -d "$(BUILDDIR)" ]; then mkdir $(BUILDDIR); fi
	@echo 'Compiling file: $<'
	$(CC) $(INC_DIRS:%=-I%) $(FLAGS) $(DFLAGS) -O3 $(LIBRARIES) -o "$(BUILDDIR)/$@" "$<" -L/usr/lib -lgdal --std=c++17
	@echo 'Building finished: $@'
