OMP_PREFIX := $(shell brew --prefix libomp)
GDAL_PREFIX := $(shell brew --prefix gdal)

ifdef ACTIVE_GPU
	CC := nvcc
	INC_DIRS := 
	FLAGS := --compiler-bindir `which mpic++` -arch=sm_70 -x cu
	LIBRARIES := -I/usr/include/gdal -lgdal
	DFLAGS := -DACTIVE_GPU=1
else
	CC := mpic++
	INC_DIRS := $(OMP_PREFIX)/include $(GDAL_PREFIX)/include
	FLAGS := -Wall -Xpreprocessor -fopenmp
	LIBRARIES := -L$(OMP_PREFIX)/lib -lomp -L$(GDAL_PREFIX)/lib -lgdal
	DFLAGS := -DACTIVE_OMP=1
endif

triton: $(SRCDIR)/main.cpp
	if [ ! -d "$(BUILDDIR)" ]; then mkdir $(BUILDDIR); fi
	@echo 'Compiling file: $<'
	$(CC) $(INC_DIRS:%=-I%) $(FLAGS) $(DFLAGS) -O3 $(LIBRARIES) -o "$(BUILDDIR)/$@" "$<" --std=c++14
	@echo 'Building finished: $@'
