/** @file ghost_ring.h
 *  @brief Persist and restore the perimeter ghost ring alongside a checkpoint.
 *
 *  The checkpoint rasters store the INTERIOR only. The ghost ring is written during a step by
 *  copy_info_to_exterior_boundaries_* and compute_extbc_values, and the interior is then modified
 *  again by wet_dry before the step ends -- so at the top of the next step the ring holds values
 *  that no longer exist anywhere in the interior. It is therefore NOT reconstructible from the
 *  restored state by any re-derivation, and a resume that does not store it starts from a ring
 *  that differs from the uninterrupted run's.
 *
 *  File layout (little-endian, one file per checkpoint per rank):
 *    header : int32 magic = 0x47524E47 ("GRNG") ; int32 version = 1 ;
 *             int32 nrows_padded ; int32 ncols_padded ; int32 sizeof_value_t
 *    body   : value_t h [nperim] ; value_t qx[nperim] ; value_t qy[nperim]
 *  where nperim = nrows*ncols - (nrows-2)*(ncols-2) and the cells appear in row-major order over
 *  the padded grid, taking every cell with r == 0, r == nrows-1, c == 0 or c == ncols-1. That
 *  ordering is generated by the same loop on both sides, so it cannot drift between writer and
 *  reader.
 */

#ifndef GHOST_RING_H
#define GHOST_RING_H

#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "constants.h"

namespace GhostRing
{
  int32_t constexpr RING_MAGIC   = 0x47524E47;  // "GRNG"
  int32_t constexpr RING_VERSION = 1;

  /** @brief Number of perimeter cells in a padded nrows x ncols grid. */
  inline int perimeter_count(int nrows, int ncols)
  {
    if (nrows <= 0 || ncols <= 0) return 0;
    if (nrows <= 2 || ncols <= 2) return nrows * ncols;
    return nrows * ncols - (nrows - 2) * (ncols - 2);
  }

  template<typename T>
  inline void gather(int nrows, int ncols, T const *arr, std::vector<T> &out)
  {
    out.clear();
    out.reserve(perimeter_count(nrows, ncols));
    for (int r = 0; r < nrows; r++)
      for (int c = 0; c < ncols; c++)
        if (r == 0 || r == nrows - 1 || c == 0 || c == ncols - 1)
          out.push_back(arr[r * ncols + c]);
  }

  template<typename T>
  inline void scatter(int nrows, int ncols, std::vector<T> const &in, T *arr)
  {
    std::size_t k = 0;
    for (int r = 0; r < nrows; r++)
      for (int c = 0; c < ncols; c++)
        if (r == 0 || r == nrows - 1 || c == 0 || c == ncols - 1)
          arr[r * ncols + c] = in[k++];
  }

  /** @brief Write the perimeter of h/qx/qy to @p path. Non-fatal on failure: a missing ring file
   *         makes a FUTURE resume fail loud, which is better than aborting a running simulation. */
  template<typename T>
  inline void write(std::string const &path, int nrows, int ncols,
                    T const *h, T const *qx, T const *qy)
  {
    std::ofstream f(path.c_str(), std::ios::binary | std::ios::trunc);
    if (!f.is_open())
    {
      std::cerr << WARN "Could not write ghost-ring side-file " << path
                << "; a resume from this checkpoint will fail." << std::endl;
      return;
    }
    int32_t hdr[5];
    hdr[0] = RING_MAGIC;
    hdr[1] = RING_VERSION;
    hdr[2] = nrows;
    hdr[3] = ncols;
    hdr[4] = static_cast<int32_t>(sizeof(T));
    f.write(reinterpret_cast<char const *>(hdr), sizeof(hdr));

    std::vector<T> buf;
    gather(nrows, ncols, h,  buf); f.write(reinterpret_cast<char const *>(buf.data()), sizeof(T) * buf.size());
    gather(nrows, ncols, qx, buf); f.write(reinterpret_cast<char const *>(buf.data()), sizeof(T) * buf.size());
    gather(nrows, ncols, qy, buf); f.write(reinterpret_cast<char const *>(buf.data()), sizeof(T) * buf.size());
    f.flush();
  }

  /** @brief Restore the perimeter of h/qx/qy from @p path. FATAL on any inconsistency: a resume
   *         that silently proceeds without the ring is exactly the defect this file exists to fix. */
  template<typename T>
  inline void read(std::string const &path, int nrows, int ncols, T *h, T *qx, T *qy)
  {
    std::ifstream f(path.c_str(), std::ios::binary);
    if (!f.is_open())
    {
      std::cerr << ERROR "Resume requires the ghost-ring side-file, but it was not found:\n"
                << "         " << path << "\n"
                << "         This checkpoint predates the ghost-ring fix. Re-run this simulation\n"
                << "         from a clean start (checkpoint_id=0)." << std::endl;
      exit(EXIT_FAILURE);
    }

    int32_t hdr[5] = {0, 0, 0, 0, 0};
    f.read(reinterpret_cast<char *>(hdr), sizeof(hdr));
    if (f.gcount() != (std::streamsize)sizeof(hdr) || hdr[0] != RING_MAGIC)
    {
      std::cerr << ERROR "Ghost-ring side-file has a bad or missing header: " << path << std::endl;
      exit(EXIT_FAILURE);
    }
    if (hdr[1] != RING_VERSION)
    {
      std::cerr << ERROR "Ghost-ring side-file version " << hdr[1] << " is not supported by this build ("
                << RING_VERSION << "): " << path << std::endl;
      exit(EXIT_FAILURE);
    }
    if (hdr[2] != nrows || hdr[3] != ncols)
    {
      std::cerr << ERROR "Ghost-ring side-file grid (" << hdr[2] << "x" << hdr[3]
                << ") does not match this run (" << nrows << "x" << ncols << "): " << path << std::endl;
      exit(EXIT_FAILURE);
    }
    if (hdr[4] != (int32_t)sizeof(T))
    {
      std::cerr << ERROR "Ghost-ring side-file was written at " << hdr[4] << "-byte precision and this build uses "
                << sizeof(T) << ": " << path << std::endl;
      exit(EXIT_FAILURE);
    }

    int const nperim = perimeter_count(nrows, ncols);
    std::vector<T> buf(nperim);
    T *dst[3] = { h, qx, qy };
    for (int a = 0; a < 3; a++)
    {
      f.read(reinterpret_cast<char *>(buf.data()), sizeof(T) * nperim);
      if (f.gcount() != (std::streamsize)(sizeof(T) * nperim))
      {
        std::cerr << ERROR "Ghost-ring side-file is truncated: " << path << std::endl;
        exit(EXIT_FAILURE);
      }
      scatter(nrows, ncols, buf, dst[a]);
    }
  }
}

#endif  // GHOST_RING_H
